version: '2'

services:
  pgsql:
    container_name: "rest_pgsql"
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=restapi
    networks:
      - mynet

  php:
    container_name: "rest_php"
    build: .
    volumes:
      - "app-files:/app/web"
      - ./log/php-fpm:/var/log/php-fpm
      - ./app/config/docker/php-fpm-7/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./app/config/docker/php-fpm-7/php.ini:/usr/local/etc/php/php.ini
      - ./app/config/docker/php-fpm-7/parameters.yml.dist:/app/app/config/parameters.yml
      - ./web:/app/web
      - ./src:/app/src
    networks:
      - mynet
    depends_on:
      - pgsql

  nginx:
    container_name: "rest_nginx"
    image: nginx:1.11.6-alpine
    dns:
      - 127.0.0.11
    volumes:
      - "app-files:/app/web"
      - ./app/config/docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - mynet
    ports:
      - "80:80"
    environment:
      - "PHP_FPM_HOST=php:9000"
      - "PHP_FPM_ROOT_DIR=/app/web"

networks:
  mynet:
    driver: bridge

volumes:
  app-files: {}
  app-db: {}