services:
  api.fos_user_manager:
    class: FOS\UserBundle\Doctrine\UserManager
    public: false
    arguments:
      - '@security.encoder_factory'
      - '@fos_user.util.username_canonicalizer'
      - '@fos_user.util.email_canonicalizer'
      - '@doctrine.orm.entity_manager'
      - '%fos_user.model.user.class%'

  api.fos_user_manipulator:
    class: FOS\UserBundle\Util\UserManipulator
    arguments: ['@api.fos_user_manager']

  api.manager.contact:
        class:        AppBundle\Manager\ContactManager
        arguments:    ['@doctrine.orm.entity_manager', '%admin_email%', '@mailer', '@twig', '@liip_imagine.cache.manager', '@vich_uploader.templating.helper.uploader_helper', '@request_stack']

  manager.user:
      class:        AppBundle\Manager\UserManager
      arguments:    ['@doctrine.orm.entity_manager', '@form.factory', '@request_stack', '@api.fos_user_manipulator', '@api.fos_user_manager']

  app.handler.when:
      class: AppBundle\Handler\WhenHandler
      arguments: ['@translator']

  api.handler.auth:
      class: AppBundle\Handler\AuthHandler

  app.locale_listener:
      class: AppBundle\EventListener\LocaleListener
      arguments: ["%kernel.default_locale%"]
      tags:
          - { name: kernel.event_subscriber }

  twig.text_extension:
     class: Twig_Extensions_Extension_Text
     tags:
         - name: twig.extension

  api.converter.contact_picture:
    class: AppBundle\Request\ContactPictureParamConverter
    arguments: ['@fos_rest.validator']
    tags:
      - { name: request.param_converter, converter: api.converter.contact_picture }

  api.event.rest_handle_listener:
    class: AppBundle\EventListener\RestListener
    arguments: ['@annotation_reader', '@fos_rest.request.param_fetcher']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController, priority: 100 }
      - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 200 }

  app_serializer.form_deserialization_visitor:
    class: AppBundle\Serializer\FormDeserializationVisitor
    arguments: [ '@jms_serializer.naming_strategy', '@jms_serializer.object_constructor' ]
    tags:
        - { name: jms_serializer.deserialization_visitor, format: form }

  app.validator.unique_user:
    class: AppBundle\Validator\Constraints\UniqueUserValidator
    arguments: ['@doctrine']
    tags:
      - { name: validator.constraint_validator, alias: app.validator.unique_user }

  app.validator.entity_exists:
    class: AppBundle\Validator\Constraints\EntityExistsValidator
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: validator.constraint_validator, alias: app.validator.entity_exists }

  app.api_doc.annotation_handler:
    class: AppBundle\AnnotationHandler\RestResultHandler
    arguments: ['@nelmio_api_doc.extractor.handler.fos_rest']
    tags:
      - { name: nelmio_api_doc.extractor.handler }
